name: sharedtheme_example_web
description: Example use of shared_theme for web
version: 1.0.0
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme/tree/master/example/packages/web

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  sharedtheme_example:
    path: ../base
  angular: ^5.0.0
  angular_components: ^0.9.0
  bootstrap_sass: ^4.1.2

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  sass_builder: ^2.0.0
